### ISSUE TITLE
Uncaught TypeError: this.definitions.reload is not a function

### ISSUE THREAD

**Issue by xu4wang** [hyperfresh/save-autorun#11]
[Enter steps to reproduce below:]
1. install the package and modify the .save.cson as below

```
"**/*.md": [
     "git add ${file}"
     "git commit -am \"update ${file}\""
]

```
1. restart atom
2. open a .md file,  modify it, save it. nothing happens
3. cmd-shift-p , `save-autoran:execute definitions` trigger the error.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [save-autorun](https://github.com/hyperfresh/save-autorun) package, v0.3.3
### Stack Trace

Uncaught TypeError: this.definitions.reload is not a function

```
At /Users/wangxu/.atom/packages/save-autorun/lib/save-autorun.coffee:111

TypeError: this.definitions.reload is not a function
    at SaveAutorun.module.exports.SaveAutorun.runDefinitions (/Users/wangxu/.atom/packages/save-autorun/lib/save-autorun.coffee:111:64)
    at atom-workspace.subscriptions.add.atom.commands.add.save-autorun:execute-definitions (/Users/wangxu/.atom/packages/save-autorun/lib/save-autorun.coffee:34:44)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  3x -2:40.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:27.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:01.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 save-autorun:execute-definitions (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "nvatom"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7
console-panel, v0.2.0
diagrams, v0.5.0
markdown-mindmap, v0.2.4
markdown-preview-enhanced, v0.7.0
merge-conflicts, v1.4.3
save-autorun, v0.3.3
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by Timemashine** [comment]
### +1

**Comment by combs** [comment]
Yup, doesn't work at all for me

**Comment by sebastientaggart** [comment]
Same error here.

**Comment by Timemashine** [comment]
I solved the Problem for me by installing the Termination Package. It is a Terminal in Atom and can run commands with key bindings.

Now i press CMD+R and the script will run in the Terminal.

**Comment by jmatsushita** [comment]
Same error here.

**Comment by tomptaylor** [comment]
same error

**Comment by eqlion** [comment]
same error
