### ISSUE TITLE
Failed to activate the save-autorun package

### ISSUE THREAD

**Issue by QinMing** [hyperfresh/save-autorun#2]
The directory looks weird. Why there is a '\' in here
 '/Users/qinming/.atom/packages/save-autorun.global.save.cson'

[Enter steps to reproduce below:]
1. install package
2. error thrown

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [save-autorun](https://github.com/hyperfresh/save-autorun) package, v0.3.0
### Stack Trace

Failed to activate the save-autorun package

```
At ENOENT: no such file or directory, open '/Users/qinming/.atom/packages/save-autorun\.global.save.cson'

Error: ENOENT: no such file or directory, open '/Users/qinming/.atom/packages/save-autorun\.global.save.cson'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:384:29)
    at new SaveDefinitions (/Users/qinming/.atom/packages/save-autorun/lib/save-definitions.coffee:19:16)
    at SaveAutorun.module.exports.SaveAutorun.activate (/Users/qinming/.atom/packages/save-autorun/lib/save-autorun.coffee:43:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:226:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:169:15)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "css-color-highlight",
      "autocomplete"
    ]
  },
  "save-autorun": {}
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v1.2.0
atom-jshint, v2.0.0
color-picker, v2.0.12
file-types, v0.5.1
git-diff-details, v0.20.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
minimap, v4.13.4
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.0
pigments, v0.15.0
save-autorun, v0.3.0
save-commands, v0.6.2

# Dev
No dev packages
```

**Comment by QinMing** [comment]
Maybe you are using Windows ?

**Comment by kaizo4613** [comment]
Yes we are using windows, sorry.

**Comment by bakana808** [comment]
you are correct, it was always using `\\`.

i've pushed an update 3815a96fe1ee9702757cd81e54f3a2a0d823fb3d (0.3.1) that uses [`path.sep`](https://nodejs.org/docs/latest/api/path.html#path_path_sep) instead, so please let me know if this has fixed the problem for you.

please reopen this if you are still experiencing the same issue.
